package uppgift4;

import java.text.DecimalFormat;
import java.util.Random;
import java.util.Scanner;

public class LottoExtra {

	public static void main(String[] args) {
		//constants		
		Scanner input = new Scanner (System.in);
		String pattern ="00";
		DecimalFormat decimalFormat = new DecimalFormat(pattern);

		String firstPrice = " 10 000 kr.";
		String secondPrice = " 5 000 kr.";
		String thirdPrice = " 1 000 kr.";
		String noPrice = " 0";
		String win;

		//User friendly messages
		System.out.println("Welcome to the Lottery:");
		System.out.println("***********************\n");
		System.out.println("Right guesses in same order as machine generated numbers attracts a price of 10 000 kr\n");
		System.out.println("Right guesses in different order as machine generated numbers attracts a price of 5 000 kr\n");
		System.out.println("Any one right guessed number in any order as machine generated numbers attracts a price of 1 000 kr\n");
		System.out.println("Please enter any two integers from 01 to 99:");


		String num = decimalFormat.format(Integer.parseInt(input.nextLine()));

		char[] randArray= randGen();
		char[] numArray= (""+num).toCharArray();



		//Conditionals
		
		if ( randArray[0]== numArray[0] && randArray[1]== numArray[1]) {
			win = firstPrice;
		}
		else if (randArray[0]== numArray[1] && randArray[1]== numArray[0]) {
			win =  secondPrice;
			
		}

		else if (randArray[0]== numArray[0] || randArray[0]== numArray[1] 
			|| randArray[1]== numArray[0] ||randArray[1]== numArray[1]) {
			win = thirdPrice;
		}
		else {
			win = noPrice;
		}

		//Final outputs
		System.out.print("The number you entered is:");

		System.out.println(num);


		System.out.print("The random number generated by machine is: ");
		System.out.print(randArray);

		System.out.print("\nTherefore, your price is:");
		System.out.print(win);
		System.out.println("\nThank you!");
		
		input.close();

			}
			
			
			
		// function to generate random numbers
			private static char[] randGen() {
				String pattern ="00";
				DecimalFormat myFormat = new DecimalFormat(pattern);
				
				Random myRandom = new Random();
				int rand = myRandom.nextInt(99);
				String formati = myFormat.format(rand);
				
				char[] formatArray= (""+formati).toCharArray();
				
				//while loop to prevent same digits from being generated
				while( formatArray[0]== formatArray[1]) {
					
					 rand = myRandom.nextInt(99);
					 formati = myFormat.format(rand);
					
					formatArray= (""+formati).toCharArray();
				
				} return formatArray;
				
					
					 
				}
		

}
	
